#!/bin/bash -e
SCRIPT_PATH=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$SCRIPT_PATH/../" && git submodule update --init --progress --jobs 4

# The compiler-rt-sigalstack.patch isn't needed starting with v5.0
# cd "$SCRIPT_PATH/../lib/compiler-rt" && git am < "$SCRIPT_PATH/../lib/compiler-rt-sigalstack.patch"

# Need this for v5.0
cd "$SCRIPT_PATH/../lib/clang" && git am < "$SCRIPT_PATH/../lib/clang-5.0-SVNVersion.inc.patch"

